export const RAMIS_WORDS = [
  "Taco Bell",
  "Triggered",
  "Roadtrax",
  "Hoed",
  "Carol Monis",
  "Freeze",
  "Chris Brown",
  "Haram",
  "Gavel",
  "Troy",
  "Big Sean",
  "28",
  "Aamna",
  "Dodge",
  "Athens",
  "Columbia",
  "Yale",
  "Canvassing",
  "Hari Vutukuru",
  "Elizabeth Warren",
  "Bad Haircut",
  "Google Notes",
  "Phone Call (Raj)",
  "Ice",
  "Meijer Football",
  "Tristan Taggart",
  "Get Some",
  "Fighting Ben",
  "Kiva Club",
  "Darwin’s Envy",
  "Nas",
  "Model UN",
  "Barbonnaise",
  "EDM",
  "Ace",
  "O'Douls",
  "Finding Nouf",
  "Lazarus",
  "Ethnic Fair",
  "Hall Pass",
  "American Pie",
  "Black Twitter",
  "Traverse City",
  "JCole",
  "Hoodie Allen",
  "Rubix Cube",
  "Ben Chander",
  "Grape Juice",
  "Mothers Day",
  "Ready to Fly",
  "Ramadan",
  "First Aid Kit",
  "Microaggression",
  "Lions",
  "AP Chem",
  "Nerd",
  "Bird",
  "Tugendhat",
];
